### ISSUE TITLE
Does it simply copy videos from someone else's list to one of my own?

### ISSUE THREAD

**Issue by wisdomtooth** [SweetIceLolly/youtube-playlist-manager#1]
I tried all functionalities, and I see it does much more than that, but that's all I needed. Well, that and copying an entire channel to a new or existing playlist.

**Comment by SweetIceLolly** [comment]
Hello! Thank you for using this tool :)
To add videos from someone else's playlist, what this tool does is first obtain the list of videos in that playlist; every playlist item is associated with a videoID; then this tool adds the video with that videoID to your specified playlist.

**Comment by wisdomtooth** [comment]
Is it the Copy function in Manage? Is there a way of selecting all without having to select one by one?

Also, do you have a function for eliminating playlist duplicates?

Also, also, I'm routinely running against quota limits with your tool. Is there a way around that?

**Comment by SweetIceLolly** [comment]
Yes, it is the Copy function in Manage. Unfortunately, there isn't a way for selecting all.. you have to select one by one. Sorry for the inconvenience!

No, there isn't a function for eliminating playlist duplicates.

I think there is a way to increase your quota limit by filling this form (https://support.google.com/youtube/contact/yt_api_form?hl=en)

**Comment by wisdomtooth** [comment]
> I think there is a way to increase your quota limit by filling this form (https://support.google.com/youtube/contact/yt_api_form?hl=en)

Thanks, I'll have a look.

> Yes, it is the Copy function in Manage. Unfortunately, there isn't a way for selecting all.. you have to select one by one. Sorry for the inconvenience!

I found an easier workaround for that music Youtube Music. What it doesn't do is copy over the whole channel to a playlist. For that I use your script, copying over a channel to a private playlist, and then use Youtube Music to copy that over to the target playlist.

> No, there isn't a function for eliminating playlist duplicates.

Cheers. I'm having a go with [Darren McConnel's script](https://github.com/Darren-McConnell/YTMusicDuplicates), but without much luck yet.

**Comment by SweetIceLolly** [comment]
Okay. Thanks again for using!! :))
