### ISSUE TITLE
The app is hanging at the authentication screen

### ISSUE THREAD

**Issue by soradevtech** [SweetIceLolly/youtube-playlist-manager#2]
Hi! I've followed the steps to create a project on Google Cloud, but after I paste in my client ID and give the app permissions (side note: I had to manually publish the app, Cloud would refuse connection at this step in testing mode), it hangs at "Authenticating...". I'm using Firefox if that helps. Let me know if you need more details.

side note: I had to manually publish the app, Cloud would refuse connection at this step in testing mode

**Comment by SweetIceLolly** [comment]
Hi! Thank you for the feedback. I have never encountered the problem you encountered. It would be great if you can open the devtool before clicking the sign in button, and then click the sign in button and see if there are any errors in the console. This may help to understand what might cause the problem.

**Comment by soradevtech** [comment]
Hey, sorry for taking so long to respond. I've taken a look at the console and here's what I get:

```javascript
Error: Promised response from onMessage listener went out of scope [background.js:22:413436](moz-extension://9acc30c9-8324-4a17-b5b2-cbbdf5754fd4/background.js)
Cookie “G_ENABLED_IDPS” has “SameSite” policy set to “Lax” because it is missing a “SameSite” attribute, and “SameSite=Lax” is the default value for this attribute. [inject.js:2704:27](moz-extension://54d4fa00-67d1-4bc0-8199-1181160befc4/public/js/inject.js)
Content Security Policy: Ignoring “'unsafe-inline'” within script-src or style-src: nonce-source or hash-source specified
Content Security Policy: Couldn’t process unknown directive ‘require-trusted-types-for’
Content Security Policy: Ignoring “'unsafe-inline'” within script-src or style-src: nonce-source or hash-source specified
Content Security Policy: Couldn’t process unknown directive ‘require-trusted-types-for’
This page is in Quirks Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”.
[iframe](https://accounts.google.com/o/oauth2/iframe#origin=https%3A%2F%2Fsweeticelolly.github.io&rpcToken=556047264.0456128)
Error: Promised response from onMessage listener went out of scope
```

This happened with Firefox dev edition in Linux Mint on my laptop (ThinkPad from 2012). After trying on my Windows desktop With Firefox dev edition, I get the same type of response but the app works. It also works in Chromium on my laptop.

I wasn't aware that my Watch Later playlist couldn't be accessed or that the general limit for videos is 160. No worries, I was able to get what I needed done in Chromium with the [Multiselect for YouTube](https://chrome.google.com/webstore/detail/multiselect-for-youtube/gpgbiinpmelaihndlegbgfkmnpofgfei) extension.

The issue's probably caused by the distro, my laptop, or the Linux version of Firefox dev. I'll look further if I need to, but feel free to close this issue. Thanks for your response.

**Comment by SweetIceLolly** [comment]
Hey no problem. Glad it worked after all! Have a great day.
